(function(g){var window=this;var t4=function(a){a=g.qd(window.document,"track",void 0,a.g);for(var b=0;b<a.length;b++)g.Md(a[b])},Wca=function(a,b){var c=new g.zx;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.H=a.H;c.F=a.F;c.J=a.J;c.g=b;return c},u4=function(a){return a.g?a.g.languageCode:a.o},v4=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.Ax(a),kind:a.B,name:a.C,id:a.xa,is_servable:a.R,is_translateable:a.H,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},w4=function(a){if(!Xca.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Yca,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},x4=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},Zca=function(a){for(var b in a)delete a[b]},y4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.kJ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},z4=function(a,b,c,d,e){g.kJ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},B4=function(a){a=void 0===a?{}:a;
var b="_"+A4++;return new z4(0,0x8000000000000,0,b,a)},F4=function(a,b,c,d,e,f){var k={};
g.Ka(k,b);g.Ka(k,a.params);g.Ka(k,c);var l={};g.Ka(l,b.Na);a.params.Na&&g.Ka(l,a.params.Na);g.Ka(l,c.Na);k.Na=l;g.X.call(this,{G:"div",L:"caption-window",P:{id:"caption-window-"+a.id,dir:k.fh==C4.rl?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},I:[{G:"span",L:"captions-text"}]});this.A=[];this.K=!1;this.F=a;this.D=[];this.H=[];this.Aa=e;this.va=f;this.C=null;this.V=.96*e;this.fa=.96*f;this.o=k;this.ua=c;this.B=this.ga["captions-text"];this.la=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.N=d/360*16;this.type=D4.ol;this.Z=this.N*E4(l);a=new g.tu(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.hB,this);a.subscribe("dragmove",this.gB,this);a.subscribe("dragend",this.fB,this);this.ca=this.da=0;a="";this.o.lh&&(a=w4(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.lh+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":$ca[this.o.textAlign]};this.la&&(b["border-radius"]=a?this.Z/
8+"px":"");g.th(this.element,b);switch(this.o.Re){case 0:case 1:case 2:g.L(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},E4=function(a){var b=1+.25*(a.Dg||0);
if(a.offset==G4.kp||a.offset==G4.np)b*=.8;return b},H4=function(a,b){var c={},d=b.background?b.background:a.o.Na.background;
if(null!=b.zd||b.background){var e=null!=b.zd?b.zd:a.o.Na.zd;d=w4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.la&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Z/8+"px")}if(null!=b.Dg||null!=b.offset)c["font-size"]=a.N*E4(b)+"px";d=1;e=b.color||a.o.Na.color;if(b.color||null!=b.yf)e=w4(e),d=null==b.yf?a.o.Na.yf:b.yf,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Mf;f==g.WZ.NONE&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+
d+")";b.Mp&&(k=e=b.Mp);var l=a.N/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case g.WZ.DROP_SHADOW:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case g.WZ.RAISED:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case g.WZ.DEPRESSED:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case g.WZ.rp:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case g.YZ.Uo:e=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case g.YZ.Xo:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case g.YZ.To:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case g.YZ.CASUAL:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case g.YZ.CURSIVE:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case g.YZ.sl:e=g.dt()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case g.YZ.Li:case g.YZ.pl:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.Na.offset);switch(e){case G4.kp:c["vertical-align"]="sub";break;case G4.np:c["vertical-align"]="super"}b.fontFamily==g.YZ.sl&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Pm&&(c["font-style"]="italic");b.underline&&
(c["text-decoration"]="underline");b.Cm&&(c.visibility="hidden");return c},I4=function(a,b,c){a.K=a.K||!!c;
var d={};g.Ka(d,a.o.Na);g.Ka(d,c||b.o);g.Ka(d,a.ua.Na);c=a.D[0];if(c&&d.background==c.background&&d.zd==c.zd&&!!d.Cm==!!c.Cm&&d.Mf==c.Mf){var e;for(e=0;e<a.D.length;e++)if(x4(d,a.D[e])){var f=a.H[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Gd("SPAN");g.th(f,H4(a,e));a.H[0].appendChild(f);e=1}a.H.length=e;a.D.length=e}else a.H.length=0,a.D.length=0,f=g.Gd("SPAN"),g.th(f,H4(a,d)),a.B.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Md(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.A.length||!b.C){if(0<e||0!=a.A.length){var m=g.Gd("BR");f.appendChild(m)}f.appendChild(g.Hd("\u00a0"));a.C=g.Hd("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Hd(l):l,m))}a.D.push(d);a.H.push(f);a.A.push(b)},J4=function(){},L4=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new K4(this);this.D=new K4(this);this.g=[];this.clear()},ada=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Zi:a,
aj:b,result:0};a=M4[a];b=M4[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{Zi:a,aj:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Zi:a,aj:b,result:2};return{Zi:a,aj:b,result:3}},bda=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,N4(a.C,b,c,d))},cda=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?bda(a,d.Hp,d.Ip,b):1==d.type&&a.A&496&&N4(a.D,d.Hp,d.Ip,b)}a.g.length=0},O4=function(){this.g=0},P4=function(){this.o=this.A=this.g=0},Q4=function(){this.timestamp=this.fd=0;
this.g=!1},R4=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new Q4}this.g=this.o=this.Nb=0;this.style=new O4;this.C=a;this.B=0},S4=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.fd){0==c&&(c=m,d=q);n=String.fromCharCode(r.fd);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.fd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.fd,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},hda=function(a,b){switch(a){case 0:return dda[(b&127)-32];
case 1:return eda[b&15];case 2:return fda[b&31];case 3:return gda[b&31]}return 0},T4=function(a){return a.A[a.Nb][a.o]},U4=function(a,b,c){2<=b&&1<a.o&&(--a.o,T4(a).fd=0);
var d=T4(a);d.timestamp=a.C.o+0;d.fd=hda(b,c);32>a.o&&a.o++},V4=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].mj(a.A[c+e][f])},W4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},X4=function(a){a.Nb=0<a.g?a.g:1;
a.o=1;W4(a,0,15)},Y4=function(a){this.B=a;
this.C=0;this.style=new O4;this.D=new R4(a);this.F=new R4(a);this.H=new R4(a);this.o=this.D;this.A=this.F;this.g=this.o},Z4=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:S4(d,c),X4(a.o),X4(a.A),d.Nb=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(S4(d,c),W4(d,d.Nb-d.g,b)):d.Nb<b&&(b=d.g),d.g=b)},$4=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},a5=function(a){a.style.set(4);
a.g=a.H;a.g.style=a.style;a.B.mode=1<<a.g.B},K4=function(a){this.o=a;
this.g=new P4;this.C=0;this.A=new Y4(a);this.D=new Y4(a);this.B=this.A},N4=function(a,b,c,d){a.g.update();
b=ada(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Zi;c=b.aj;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&U4(e,0,b),c&96&&U4(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&S4(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Nb;break;case 3:if(d!=c.Nb){if(d<c.g&&(d=c.g,d==c.Nb))break;var f=1+c.Nb-c.g,k=1+d-c.g;V4(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));W4(c,b,e)}}c.Nb=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:U4(b.g,0,32);break a;case 48:57==c?(b=b.g,T4(b).fd=0,32>b.o&&b.o++):U4(b.g,1,c&15)}break;case 2:c&32&&U4(b.g,2,c&31);break;case 3:c&32&&U4(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:$4(b);break;
case 33:b=b.g;1<b.o&&(--b.o,T4(b).fd=0);break;case 36:b=b.g;d=T4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:Z4(b,2,d);break;case 38:Z4(b,3,d);break;case 39:Z4(b,4,d);break;case 40:U4(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.H;d.g=15;d.style.set(4);X4(d);a5(b);break;case 43:a5(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:S4(a,d)}W4(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Nb){++a.Nb;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Nb<a.g&&(a.Nb=a.g));b=a.Nb-a.g+1;S4(a,d);V4(a,b,b+1,a.g-1);W4(a,a.Nb,1)}break;case 46:W4(b.A,0,15);break;case 47:S4(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;$4(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},b5=function(){},c5=function(a){this.A=a;
this.o=null},f5=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?d5.tl:d5.Mi;a=g.wp("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");e5(d,e,k,b,f,a.firstChild,{},c)},e5=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Pm=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");g5.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new y4(a,b,c,d,n.nodeValue,e||0<m,g.hc(k)?void 0:k));else{var q={};g.Ka(q,k);e5(a,b,c,d,e||0<m,n,q,l)}}},h5=function(){this.A={};
this.o=null},i5=function(a){this.o={};
this.C={};this.D={};this.A="_"+A4++;this.B=a},j5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},k5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},l5=function(a,b){var c=j5(a,b);
if(void 0!=c)return c},m5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return g5.test(c),c},n5=function(a,b){var c={},d=b.getAttribute("ws");
g.Ka(c,d?a.D[d]:a.B);d=l5(b,"mh");null!=d&&(c.bn=d);d=l5(b,"ju");null!=d&&(c.textAlign=d);d=l5(b,"pd");null!=d&&(c.fh=d);d=m5(b,"wfc");null!=d&&(c.windowColor=d);d=j5(b,"wfo");void 0!=d&&(c.lh=d/255);return c},o5=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ka(c,a.C[d]);d=l5(b,"ap");null!=d&&(c.Re=d);d=j5(b,"cc");null!=d&&(c.my=d);d=j5(b,"ah");null!=d&&(c.ag=d);d=j5(b,"rc");null!=d&&(c.Fk=d);d=j5(b,"av");null!=d&&(c.sg=d);return c},p5=function(a,b,c){var d={};
g.Ka(d,o5(a,b));g.Ka(d,n5(a,b));c?x4(d,a.B)?(c=a.A,d=a.B):c="_"+A4++:c=b.getAttribute("id")||"0";a=j5(b,"t");b=j5(b,"d")||0x8000000000000;return new z4(a,b,0,c,d)},q5=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},r5=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},s5=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},t5=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new L4(!1);this.A.A=1<<this.o},u5=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=s5(a);b.toString(16);if(1380139777!=b)return!1;a.version=r5(a);if(1<a.version)return!1;r5(a);r5(a);r5(a);return!0},ida=function(){this.o=[];
this.g=[]},v5=function(a,b){return b?a.g.concat(a.o):a.g},w5=function(a,b){switch(b.B){case "asr":var c=a.o;
g.ob(c,(0,g.z)(b.K,b))||c.push(b);break;default:c=a.g,g.ob(c,(0,g.z)(b.K,b))||c.push(b)}},x5=function(){this.o=null},y5=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Pm=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new y4(b,c,d,e.id,q.nodeValue,f||0<n,g.hc(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Ka(r,l);y5(a,b,c,d,e,!0,q,r,m)}}},z5=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},A5=function(a){g.I.call(this);
this.jr=!!a;this.o=new ida;this.C=[];this.g=null},B5=function(a){var b={};
if(a=u4(a))b.lang=a,jda.test(a)&&(b.fh=C4.rl);return b},kda=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new x5),a.g.g(b,d);b=g.wp(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new i5(B5(c)):a.g=new h5:a.g=new c5(B5(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new q5(b,0,0);f=u5(k)}if(f)return a.g||(a.g=new t5(e,c)),a.g.g(b,d)}catch(l){g.Bs(l)}return[]},C5=function(a){A5.call(this,a.gj);
this.B=void 0;this.A=null;this.C=a.captionTranslationLanguages},D5=function(){this.La=[]},E5=function(a,b,c,d,e,f){g.I.call(this);
this.K=b;this.B=new D5;this.g=null;this.D=d;this.J=f;this.o=this.A=null;this.N=c;this.C=e||!1;this.F=new g.O(this.xr,1E3,this);g.J(this,this.F);this.H=new g.ou(this);g.J(this,this.H);this.H.O(b,"seekto",this.ks);this.ks(b.getCurrentTime());this.xr()},F5=function(a,b){A5.call(this);
this.D=a;this.M=b;this.A=null;this.B=!1},G5=function(a,b,c,d,e,f){F4.call(this,a,b,c,d,e,f);
this.type=D4.nl},H5=function(a,b,c,d,e,f){F4.call(this,a,b,c,d,e,f);
g.L(this.element,"ytp-caption-window-rollup");this.type=D4.ql;this.J=this.R=0;this.U=window.NaN;this.ra=null;this.X=new g.O(this.sG,433,this);g.J(this,this.X)},I5=function(a){if(!a.R){var b=g.Gd("SPAN");
g.th(b,H4(a,a.o.Na));a.B.appendChild(b);b.appendChild(g.Hd("M"));var c=b.offsetHeight,d=g.Gd("BR");b.appendChild(d);b.appendChild(g.Hd("M"));a.R=b.offsetHeight-c;a.B.removeChild(b)}return a.R},J5=function(a,b,c,d){A5.call(this,d);
c=c||g.Ps(a).hl||"";c=c.split("_").join("-");this.D=g.Rs(a,{hl:c});this.B=b;this.F={};this.A=null},M5=function(a){g.aS.call(this,a);
g.$r();this.B=g.U(a);this.A=a.getVideoData();this.ra=g.GO(a);this.M=a;var b=null,c=g.Cr("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.pr(c));this.Z=b;this.D={Na:{}};this.J={Na:{}};this.N=[];this.R={};this.aa={};this.X=!1;this.ua="1"==this.A.tb.cc_auto_caps||"1"==this.B.V.cc_auto_caps;this.H="3"==this.B.B&&!!a.app.C&&!!a.app.C.g.textTracks;c=b=this.o=this.C=this.F=this.K=this.V=this.la=null;this.H||(b=new g.xp(this.Mv,void 0,this),g.J(this,b),c=new g.O(this.LH,2E3,this),g.J(this,c));
this.ca=b;this.fa=c;this.U=new g.ou(this);g.J(this,this.U);this.H||this.U.O(a,"resize",this.wo);this.U.O(a,"onPlaybackAudioChange",this.eE);this.U.O(a,"crn_captions",this.NA,this);this.U.O(a,"crx_captions",this.OA,this);K5(this,L5(this,"display-settings")||{})},N5=function(a){if(a.A.captionTracks.length)var b=a.g.pf().Fp;
if("FORCED_ON"==b||1==a.B.Ve||1==a.A.Ve||"alwayson"==g.sH(a.A,"yt:cc"))return!0;if(2==a.B.Ve){var c=L5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.sH(a.A,"yt:cc")},O5=function(a,b){if(a.C){var c=v5(a.C.o,b||a.ua);
if(a.F&&a.F.g)return a.F.g;for(var d=[a.A.Ue,a.B.Ue,g.sH(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(u4(c[f])==d[e])return c[f];return a.F&&a.F.Ml?a.F.Ml:c[0]||a.F&&a.F.Fh}return null},P5=function(a,b){for(var c=a.M.app.C.g.textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},Q5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.X=c);a.o=b;a.load(d)},lda=function(a,b){var c=g.yQ(a.ra,!0).height;
if(!c)return null;var d=a.ra.Da();switch(null!=b.params.bn?b.params.bn:b.params.kI?D4.ql:1<b.o.length?D4.nl:D4.ol){case D4.nl:return new G5(b,a.D,a.J,c,d.width,d.height);case D4.ql:return new H5(b,a.D,a.J,c,d.width,d.height);default:return new F4(b,a.D,a.J,c,d.width,d.height)}},K5=function(a,b,c){var d=R5.Na;
a.D={};g.Ka(a.D,R5);a.D.Na={};g.Ka(a.D.Na,d);a.J={Na:{}};var e=b.backgroundOverride?a.J:a.D,f=b.background||d.background;g5.test(f);e.Na.background=f;e=b.colorOverride?a.J:a.D;f=b.color||d.color;g5.test(f);e.Na.color=f;e=b.windowColorOverride?a.J:a.D;f=b.windowColor||R5.windowColor;g5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.J:a.D;f=b.backgroundOpacity;null==f&&(f=d.zd);e.Na.zd=f;e=b.fontSizeIncrementOverride?a.J:a.D;f=b.fontSizeIncrement;null==f&&(f=d.Dg);e.Na.Dg=f;e=b.textOpacityOverride?
a.J:a.D;f=b.textOpacity;null==f&&(f=d.yf);e.Na.yf=f;e=b.windowOpacityOverride?a.J:a.D;f=b.windowOpacity;null==f&&(f=R5.lh);e.lh=f;e=b.charEdgeStyleOverride?a.J:a.D;f=b.charEdgeStyle;null==f&&(f=d.Mf);e.Na.Mf=f;e=b.fontFamilyOverride?a.J:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Na.fontFamily=f;a.loaded&&a.wo();c&&S5(a,"display-settings",b)},U5=function(a,b){if(b&&!a.K){var c=B4({fh:C4.ll,
lang:"en"});a.K=[c,new y4(c.start,c.end-c.start,0,c.id,g.Q("YTP_SAMPLE_SUBTITLES"))];g.SO(a.g,a.K)}else!b&&a.K&&(T5(a,a.K),a.K=null)},T5=function(a,b){g.UO(a.g,b);
(0,g.G)(b,function(a){g.yb(this.N,a)},a);
a.ca.Mh()},mda=function(a,b){return a&&g.u(a)&&g5.test(a)?a:b},nda=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},oda=function(a,b){if(a&&g.u(a)){var c=V5.indexOf(a);
return-1!=c?c:b}return b},pda=function(a,b){if(a&&g.u(a)){var c=W5.indexOf(a);
return-1!=c?c:b}return b},qda=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?g.ad(a,-2,4):b},L5=function(a,b){if(!a.Z)return null;
try{var c=a.Z.get(b)}catch(d){a.Z.remove(b)}return c},S5=function(a,b,c){if(a.Z)try{a.Z.set(b,c)}catch(d){}};
g.Py.prototype.Gj=g.ca(4,function(a){return(a=this.Pf(a))?a.o:0});
g.SB.prototype.Gj=g.ca(3,function(){return 0});
g.zx.prototype.K=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
var Xca=/^#(?:[0-9a-f]{3}){1,2}$/i,Yca=/#(.)(.)(.)/,jda=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,G4={kp:0,NORMAL:1,np:2},W5="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),V5=["none","raised","depressed","uniform","dropShadow"],g5=/^#(?:[0-9a-f]{3}){1,2}$/i;var X5={So:0,mL:1,Bw:2},$ca=["left","right","center"],C4={ll:0,rl:1,EL:2,qJ:3},d5={bM:0,Mi:5,tl:6},D4={ol:0,nl:1,ql:2};var R5={windowColor:g.XZ.fl,lh:0,textAlign:X5.Bw,Re:7,ag:50,sg:100,Na:{background:g.XZ.fl,zd:.75,Mf:g.WZ.NONE,color:g.XZ.ul,fontFamily:g.YZ.pl,Dg:0,yf:1,offset:G4.NORMAL}};g.p(y4,g.kJ);g.p(z4,g.kJ);var A4=0;g.p(F4,g.X);g.h=F4.prototype;g.h.hB=function(a,b){var c=g.Kh(this.element,this.element.parentElement);this.da=a-c.x;this.ca=b-c.y;g.L(this.element,"ytp-dragging")};
g.h.gB=function(a,b){var c=g.Nh(this.element),d=a-this.da-.02*this.Aa,e=b-this.ca-.02*this.va,f=(d+c.width/2)/this.V*3;f=Math.floor(g.ad(f,0,2));var k=(e+c.height/2)/this.fa*3;k=Math.floor(g.ad(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.V;d=100*g.ad(d,0,1);c=(e+k/2*c.height)/this.fa;c=100*g.ad(c,0,1);this.F.params.Re=l;this.F.params.sg=c;this.F.params.ag=d;this.o.Re=l;this.o.sg=c;this.o.ag=d;this.Tu()};
g.h.fB=function(){g.M(this.element,"ytp-dragging")};
g.h.Tu=function(){this.pg(this.A)};
g.h.pg=function(a){var b=Math.min(this.Dq(),this.V),c=this.Cq();g.th(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.xl(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.ag+2,e=this.o.Re;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.sg+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.th(this.element,a)};
g.h.xl=function(a){var b;for(b=0;b<a.length&&a[b]==this.A[b];b++);if(this.K||this.A.length>b)b=0,this.K=!1,this.A=[],this.D=[],this.H=[],this.C=null,g.Jd(this.B);for(;b<a.length;b++)I4(this,a[b])};
g.h.Dq=function(){return 0};
g.h.Cq=function(){return 0};
g.h.toString=function(){return g.X.prototype.toString.call(this)};J4.prototype.B=function(){};L4.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
L4.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var M4=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];O4.prototype.set=function(a){this.g=a};
O4.prototype.get=function(){return this.g};
P4.prototype.clear=function(){this.g=0};
P4.prototype.update=function(){this.g=2==this.g?1:0};
P4.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
Q4.prototype.mj=function(a){this.fd=a.fd;this.timestamp=a.timestamp;this.g=a.g};
Q4.prototype.reset=function(){this.timestamp=this.fd=0;this.g=!1};
R4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0==d.fd?a+"_":a+String.fromCharCode(d.fd)}a+="\n"}return a};
R4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Nb=1};
var dda=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],eda=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],fda=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],gda=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Y4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
K4.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};b5.prototype.reset=function(){};g.p(c5,b5);c5.prototype.g=function(a){var b=[];this.o||(this.o=B4(this.A),b.push(this.o));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())f5(c.value,this.o.id,b);return b};g.p(h5,b5);
h5.prototype.g=function(a){var b=[];this.o||(this.o=B4(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=B4());
var k={};f&&(g.Ka(k,f.params),f=f.params.Na)&&(k.Na={},g.Ka(k.Na,f));e.getAttribute("rc")&&(k.Fk=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.my=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Re=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ag=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.sg=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.fh=C4.rl,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.fh=C4.ll));e.getAttribute("bc")&&(k.Na||(k.Na={}),k.Na.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.Na||(k.Na={}),k.Na.zd=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.Na||(k.Na={}),k.Na.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.kI=(0,window.parseInt)(e.getAttribute("sd"),10));
f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new z4(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],f5(a,this.o.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(i5,b5);
i5.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ma(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ma(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":b=a.getAttribute("id");var e=this.o,f={},k=a.getAttribute("p");k&&g.Ka(f,this.o[k]);k=k5(a,"b");null!=k&&(f.bold=k);k=k5(a,"i");null!=k&&(f.Pm=k);k=k5(a,"u");null!=k&&(f.underline=k);k=l5(a,"et");
null!=k&&(f.Mf=k);k=l5(a,"of");null!=k&&(f.offset=k);k=m5(a,"bc");null!=k&&(f.background=k);k=m5(a,"ec");null!=k&&(f.Mp=k);k=m5(a,"fc");null!=k&&(f.color=k);k=l5(a,"fs");void 0!=k&&k!=g.YZ.Li&&(f.fontFamily=k);k=j5(a,"sz");void 0!=k&&(f.Dg=k/100-1);k=j5(a,"bo");void 0!=k&&(f.zd=k/255);a=j5(a,"fo");void 0!=a&&(f.yf=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=n5(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=o5(this,a)}c=[];if(d)for(a={},b=void 0,d=g.ma(d.childNodes),e=
d.next();!e.done;e=d.next())switch(e=e.value,e.tagName){case "w":var l=p5(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=uc;f=[];k=e.getAttribute("w")||this.A;var q=!!k5(e,"a"),r=j5(e,"t")||0,v=j5(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?d5.tl:d5.Mi;n=this.o[e.getAttribute("p")];for(var D=e.childNodes,C=0;C<D.length;C++){var B=D[C];0<C&&(q=!0);if("s"==B.tagName){var V=B;B=r;var Z=v,za=k,qa=q,sa=m,Zd=V.textContent?V.textContent:
"",Rb=this.o[V.getAttribute("p")];V=j5(V,"t")||0;B=new y4(B+V,Z-V,sa,za,Zd,qa,Rb)}else B=new y4(r,v,m,k,B.textContent||"",q,n);f.push(B)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var uc=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=p5(this,e,!0),c.push(l));e=g.ma(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}return c};g.p(q5,J4);q5.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+A4++;c=c/1E3-this.F;d=d/1E3-this.F;var k=d5.Mi;a=new z4(c,d-c,k,f,{textAlign:X5.So,Re:0,ag:2.5*b,sg:5.33*a});e=new y4(c,d-c,k,f,e);this.A.push(a);this.A.push(e)}};
g.p(t5,b5);t5.prototype.g=function(a){a=new q5(a,0,this.B);if(u5(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=s5(a)*(1E3/45)),a.C=r5(a);0<a.C;a.C--){var b=r5(a),c=r5(a),d=r5(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,Hp:c,Ip:d,order:b.g.length}))}cda(this.A,a);return a.A}return[]};
t5.prototype.reset=function(){this.A.clear()};g.p(x5,b5);
x5.prototype.g=function(a,b){for(var c=[],d=a.split(rda),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!sda.test(f)){var l=Y5.exec(f);if(l&&3<=l.length){var m=z5(l[1]);l=z5(l[2])-m;m+=k;f=f.substring(Y5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");Y5.lastIndex=0;var n=f;f={};this.o||(this.o=B4({bn:D4.ol}),c.push(this.o));var q=this.o;k=d5.Mi;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new y4(m,l,k,q.id,n,!1,g.hc(f)?void 0:f));else{n=n.split(tda);1!=n.length&&(k=d5.tl,q="_"+uda++,q=new z4(m,l,k,
q,{}),c.push(q));for(var r=m,v=0;v<n.length;v++){var D=n[v];if(0==v%2){var C=g.wp("<html>"+D+"</html>");if(C.getElementsByTagName("parsererror").length){var B=C.createElement("span");B.appendChild(C.createTextNode(D))}else B=C.firstChild;y5(this,r,l-(r-m),k,q,0<v,B,f,c)}else r=z5(D)}}}Y5.lastIndex=0}}return c};
var uda=0,sda=/^NOTE/,rda=/(?:\r\n|\r|\n){2,}/,Y5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),tda=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(A5,g.I);A5.prototype.Fc=function(){this.g=null};
A5.prototype.W=function(){g.I.prototype.W.call(this);this.Fc()};
A5.prototype.Bu=function(){return!1};g.p(C5,A5);g.h=C5.prototype;g.h.Wm=function(a,b){var c=this.Lh(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Fc();this.A=g.Ys(c,{format:"RAW",kb:d,withCredentials:!0})};
g.h.Xm=function(a,b,c,d){this.B=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())w5(this.o,c.value);a()};
g.h.Lh=function(a){var b=a.J,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.Rs(b,c)};
g.h.Fc=function(){A5.prototype.Fc.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Fc();A5.prototype.W.call(this)};D5.prototype.contains=function(a){a=g.Hb(this.La,a);return 0<=a||0>a&&1==(-a-1)%2};
D5.prototype.length=function(){return this.La.length/2};g.p(E5,g.I);g.h=E5.prototype;g.h.W=function(){g.I.prototype.W.call(this);this.o&&this.o.abort()};
g.h.ks=function(a){var b=this.g;this.g=g.kb(this.N.Ze(a).g);b!=this.g&&this.J&&this.J()};
g.h.reset=function(){this.B=new D5;this.o&&(this.o.abort(),this.o=null)};
g.h.xr=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.dg(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.K.getCurrentTime())){a=this.g;a=a.g.Wh(a);if(!this.B.contains(a.g[0].oa)){var b=g.nB(g.vB(a,{})),c={format:"RAW",Rc:(0,g.z)(this.oG,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.Ys(b,c);this.A=a;b=this.B;c=this.A.g[0].oa;var d=g.Hb(b.La,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.La[d-1]&&d<b.La.length&&1==b.La[d]-c?(g.wb(b.La,d),g.wb(b.La,d-1)):0<d&&1==
c-b.La[d-1]?b.La[d-1]=c:d<b.La.length&&1==b.La[d]-c?b.La[d]=c:(g.Eb(b.La,d,0,c),g.Eb(b.La,d+1,0,c)))}this.g=g.kb(a.g)}this.F.start()};
g.h.oG=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(F5,A5);g.h=F5.prototype;g.h.Wm=function(a,b){this.Fc();var c=this.D.g[a.o];if(c){var d=1E3*c.index.Gj(c.index.ye()),e=g.U(this.M).Rd;this.A=new E5(new g.AA,this.M,c,function(c,e){b(c,a,e,d)},e,(0,g.z)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.B=!0)},this))}};
g.h.Bu=function(){var a=this.B;this.B=!1;return a};
g.h.Xm=function(a){g.U(this.M).Rd?(w5(this.o,new g.zx({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),w5(this.o,new g.zx({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):w5(this.o,new g.zx({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Fc=function(){A5.prototype.Fc.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.Lh=function(){return""};
g.h.W=function(){this.Fc();A5.prototype.W.call(this)};g.p(G5,F4);G5.prototype.xl=function(a){var b=this.F.o;F4.prototype.xl.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ka(d,c.o);g.Ka(d,vda);var e=c.o;var f=d}I4(this,c,d)}};
var vda={Cm:!0};g.p(H5,F4);g.h=H5.prototype;g.h.Tu=function(){g.Ap(this.X)};
g.h.sG=function(){g.M(this.element,"ytp-rollup-mode");this.pg(this.ra,!0)};
g.h.Dq=function(){return this.J};
g.h.Cq=function(){return this.F.params.Fk*I5(this)};
g.h.pg=function(a,b){this.ra=a;if(I5(this)){for(var c=0,d=0;d<this.A.length&&c<a.length;d++)this.A[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.A.concat(a.slice(c)));c=this.J;this.J=0;F4.prototype.pg.call(this,a);this.J=Math.max(c,this.B.offsetWidth+1);c=this.F.params.Fk*I5(this)-this.B.offsetHeight;c!=this.U&&(b||(0,window.isNaN)(this.U)||(g.L(this.element,"ytp-rollup-mode"),this.X.rb()),g.th(this.B,"transform",c?"translateY("+c+"px)":""),this.U=c);F4.prototype.pg.call(this,a)}else F4.prototype.pg.call(this,
a)};g.p(J5,A5);g.h=J5.prototype;g.h.Wm=function(a,b){var c=this.Lh(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Fc();this.A=g.Ys(c,{format:"RAW",kb:d,withCredentials:!0})};
g.h.Xm=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.jr&&(b.asrs=1);d=g.Rs(d,b);b=(0,g.z)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),D=m.getAttribute("id"),C="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");w5(d,new g.zx({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:v,id:D,is_servable:!0,is_translateable:C,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.F[l.languageCode]=l.languageName,this.C.push(new g.yx(l))}a()},this);
this.Fc();this.A=g.Ys(d,{format:"RAW",kb:b,withCredentials:!0})};
g.h.Lh=function(a){var b=this.D,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=u4(a));return b=g.Rs(b,c)};
g.h.Fc=function(){A5.prototype.Fc.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Fc();A5.prototype.W.call(this)};g.p(M5,g.aS);g.h=M5.prototype;g.h.W=function(){this.H?t4(this.M.app.C):U5(this,!1);g.aS.prototype.W.call(this)};
g.h.Vr=function(){return this.H?!this.A.sa:this.A.captionTracks.length&&this.g.pf().Fh?!0:N5(this)};
g.h.load=function(a){g.aS.prototype.load.call(this);this.F=this.g.pf();if(this.C||a)this.o?(this.H&&!this.B.experiments.g("legacy_native_caption_api")?P5(this,!0):a?this.ou(a,this.o):3!=this.g.Ba()&&this.C.Wm(this.o,(0,g.z)(this.ou,this)),this.g.na("captionschanged",v4(this.o))):this.g.na("onCaptionsTrackListChanged");else{var b;a=this.A;a.sa||g.U(this.M).Rd&&null!=a.ma&&null!=a.ma.g.rawcc?b=new F5(this.A.ma,this.g):this.A.captionTracks.length?b=new C5(this.A):b=new J5(this.A.hj,this.A.videoId,this.A.Ue||
this.B.Ue||g.sH(this.A,"yt:cc_default_lang")||this.B.Ic,this.A.gj);this.C=b;b.Xm((0,g.z)(this.RG,this),!0,this.H?"vtt":void 0,this.g.pf())}};
g.h.unload=function(){this.H?this.B.experiments.g("legacy_native_caption_api")?t4(this.M.app.C):this.o&&P5(this,!1):(this.fa&&g.Bp(this.fa),g.VO(this.g,"captions"),this.N=[],this.C&&this.C.Fc(),this.K&&g.SO(this.g,this.K),this.wo());g.aS.prototype.unload.call(this);var a=g.W(this.g.app);a&&a.D&&g.JH(a.D.A);this.g.na("captionschanged",{})};
g.h.RG=function(){if(this.X||N5(this))var a=O5(this,this.X);if(this.H){for(var b=v5(this.C.o,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Ax(e),srclang:u4(e),src:this.C.Lh(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.Ed("TRACK",f))}a=this.M.app.C;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.M.app.C.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.B.experiments.g("legacy_native_caption_api")&&this.U.O(c.textTracks,"change",this.SG)}else!this.o&&a&&Q5(this,
a),this.g.na("onCaptionsTrackListChanged"),this.g.na("onApiChange")};
g.h.SG=function(){for(var a=this.M.app.C.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=v5(this.C.o,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&Q5(this,b,!0)};
g.h.nI=function(){this.B.experiments.g("legacy_native_caption_api")?this.loaded&&!this.H&&this.unload():!this.o&&this.H||this.unload()};
g.h.ou=function(a,b,c,d){if(a){this.C.Bu()&&(this.N=[],g.VO(this.M,"captions"),this.ca.Mh());a=kda(this.C,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:u4(b)};b.g&&(c.fromLangCode=b.o);g.MO(this.g,"cc",c);if(this.o!=(this.F&&this.F.Fh)){if(this.X&&!g.EE(this.B)&&!g.FE(this.B)){g.Bp(this.fa);b=B4({Re:0,ag:5,sg:5,Fk:2,textAlign:X5.So,fh:C4.ll,lang:"en"});this.V=[b];c=g.Q("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.la||(d=new g.xP(g.us()),g.J(this,d),this.la=d.element);d=b.end-b.start;
var e=g.Ax(this.o);e&&this.V.push(new y4(b.start,d,0,b.id,e));this.V.push(new y4(b.start,d,0,b.id,c[0]),new y4(b.start,d,0,b.id,this.la,!0),new y4(b.start,d,0,b.id,c[1],!0));g.SO(this.g,this.V);this.fa.rb()}if(this.X||g.EE(this.B))S5(this,"module-enabled",!0),this.F&&(this.F.g=this.o);(b=g.W(this.g.app))&&b.D&&g.JH(b.D.A)}g.SO(this.g,a);this.X=!1}};
g.h.NA=function(a){this.N.push(a);this.ca.Mh()};
g.h.OA=function(a){g.yb(this.N,a);this.ca.Mh()};
g.h.yH=function(a){if(a instanceof z4){var b=this.R[a.id];b&&b.F!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=lda(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.LH=function(){T5(this,this.V);this.V=null};
g.h.Mv=function(){this.ca.stop();Zca(this.aa);this.N.sort(g.nJ);var a=this.N;if(this.K){var b=(0,g.Od)(a,function(a){return-1==this.K.indexOf(a)},this);
b.length&&(a=b)}(0,g.G)(a,this.yH,this);g.Ub(this.R,function(a,b){this.aa[b]?(a.element.parentNode||g.$O(this.g,a.element,4),a.pg(this.aa[b])):(a.dispose(),delete this.R[b])},this)};
g.h.Su=function(){K5(this,{},!0)};
g.h.Yl=function(){var a=R5.Na;a={background:a.background,backgroundOpacity:a.zd,charEdgeStyle:a.Mf,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Dg,textOpacity:a.yf,windowColor:R5.windowColor,windowOpacity:R5.lh};var b=L5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.zo=function(a,b){var c={};g.Ka(c,L5(this,"display-settings"));g.Ka(c,a);K5(this,c,b);this.g.T("captionssettingschanged")};
g.h.wo=function(){!this.H&&this.loaded&&(g.Ub(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.Mv())};
g.h.jn=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.ad(b,-2,4);this.zo({fontSizeIncrement:c});return c;case "reload":b&&!this.H&&Q5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.B.bb&&S5(this,"module-enabled",!!b);break;case "track":if(!this.C)return{};if(b){if(this.H)break;if(!g.Ea(b))break;if(g.hc(b)){Q5(this,null,!0);break}for(var d=v5(this.C.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?Wca(f,
b.translationLanguage):f)}!c||c==this.o&&this.loaded||Q5(this,c,!0)}else return this.loaded&&this.o&&this.o!=(this.F&&this.F.Fh)?v4(this.o):{};return"";case "tracklist":return this.C?(0,g.H)(v5(this.C.o,b&&b.includeAsr),function(a){return v4(a)}):[];
case "translationLanguages":return this.C?this.C.C:[];case "displaySettings":c=this.Yl();if(g.EE(this.B)&&b&&g.Ea(b))if(b.reset)this.Su();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=mda(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=nda(b[d],c[d]);break;case "charEdgeStyle":f[d]=oda(b[d],c[d]);break;case "fontSizeIncrement":f[d]=qda(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=pda(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.zo(f,!0);c=this.Yl()}c.fontFamilyOption=W5[c.fontFamily];c.charEdgeStyle=V5[c.charEdgeStyle];return c;case "sampleSubtitles":this.H||void 0==b||U5(this,!!b);break;case "xmlTrack":b&&this.B.bb&&(this.H||Q5(this,new g.zx({languageName:b.name}),!1,b.xml))}};
g.h.LA=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.B.bb&&a.push("stickyLoading","xmlTrack");return a};
g.h.MA=function(){var a=this.o;return a?{cc:a.F}:{}};
g.h.Av=function(){this.loaded&&this.o?(S5(this,"module-enabled",!1),this.unload()):Q5(this,this.o||O5(this,!0),!0)};
g.h.eE=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),this.Vr()&&this.load())};g.YS.captions=M5;})(_yt_player);
